import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";

import { SignupUser } from "@/components/signupUser";
import { UserSignupProvider } from "@/contexts/UserSignupContext";

export default function Signup(): ReactElement {
  return (
    <>
      <Head>
        <title>Caramelo - Pet na web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="container xl:max-w-screen-xl flex items-center mx-auto h-full">
          <div className="flex w-full h-screen flex-1 bg-primary">
            <div className="relative w-full mx-10">
              <Image
                className="object-contain"
                src="/paw-print.svg"
                alt="Drawing of a french bulldog sitting looking back at you"
                fill
                priority
              />
            </div>
          </div>
          <div className="flex-1 relative">
            <UserSignupProvider>
              <SignupUser />
            </UserSignupProvider>
          </div>
        </div>
      </main>
    </>
  );
}
