import Head from "next/head";
import Image from "next/image";
import { ReactElement, useContext, useState } from "react";
import { useForm } from "react-hook-form";

import { AuthContext, ISignInData } from "@/contexts/AuthContext";
import { VisibilityOff } from "@mui/icons-material";
import Visibility from "@mui/icons-material/Visibility";
import {
  Box,
  FormControl,
  IconButton,
  InputAdornment,
  InputLabel,
  OutlinedInput,
  TextField,
  Typography,
} from "@mui/material";

export default function Home(): ReactElement {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [showPassword, setShowPassword] = useState(false);

  const handleClickShowPassword = (): void => setShowPassword((show) => !show);

  const handleMouseDownPassword = (
    event: React.MouseEvent<HTMLButtonElement>,
  ): void => {
    event.preventDefault();
  };

  const { register, handleSubmit } = useForm<ISignInData>();

  const { signIn } = useContext(AuthContext);

  async function handleSignIn(data: ISignInData): Promise<void> {
    await signIn(data);
  }

  return (
    <>
      <Head>
        <title>Caramelo - Pet on the web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="container xl:max-w-screen-xl flex items-center mx-auto h-full">
          <div className="flex w-full h-screen flex-1 bg-primary">
            <div className="mx-10 relative w-full">
              <Image
                className="object-contain"
                src="/logo.svg"
                alt="Drawing of a french bulldog sitting looking back at you"
                fill
                priority
              />
            </div>
          </div>
          <div className="flex-1">
            <Typography
              variant="h1"
              className="text-center font-chicle text-secondary mb-12 px-10"
            >
              Caramelo
            </Typography>
            <form
              className="flex-col bg-white px-10"
              onSubmit={handleSubmit(handleSignIn)}
              autoComplete="off"
            >
              <div className="flex flex-col text-sm rounded-md space-y-6">
                <TextField
                  {...register("email")}
                  required
                  type="email"
                  label="Email"
                  placeholder="you@email.com"
                  value={email}
                  onChange={(e): void => setEmail(() => e.target.value)}
                />
                <FormControl variant="outlined">
                  <InputLabel htmlFor="outlined-adornment-password">
                    Password
                  </InputLabel>
                  <OutlinedInput
                    {...register("password")}
                    id="outlined-adornment-password"
                    required
                    type={showPassword ? "text" : "password"}
                    label="Password"
                    placeholder="Strong password"
                    value={password}
                    onChange={(e): void => setPassword(() => e.target.value)}
                    endAdornment={
                      <InputAdornment position="end">
                        <IconButton
                          aria-label="toggle password visibility"
                          onClick={handleClickShowPassword}
                          onMouseDown={handleMouseDownPassword}
                        >
                          {showPassword ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                      </InputAdornment>
                    }
                  />
                </FormControl>
              </div>
              <button
                className="mt-12 w-full border p-3 bg-secondary font-bold text-white rounded-md hover:bg-hoverSecondary ease-in-out duration-300"
                type="submit"
              >
                Sign in
              </button>
              <div className="mt-5 flex justify-between text-md text-gray-600">
                <a href="#">Forgot password?</a>
                <a href="#">Sign up</a>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
