import Head from "next/head";
import { useRouter } from "next/router";
import { ReactElement, useContext, useEffect, useState } from "react";

import { AuthContext } from "@/contexts/AuthContext";
import { findPetByUsername, IPet } from "@/services/petService";

export default function Dashboard(): ReactElement {
  const { user, setUser } = useContext(AuthContext);
  const [pet, setPet] = useState<IPet | null>();
  const router = useRouter();
  const { username } = router.query;

  useEffect(() => {
    (async (): Promise<void> => {
      if (user && username) {
        const pet = await findPetByUsername(username as string);

        if (pet) {
          setPet(pet);
        }
        console.log("PET from back", pet);
      }
    })();
  }, [user, username]);

  return (
    <>
      <Head>
        <title>{pet?.name}&apos;s profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center w-screen h-screen">
        <h1>PET {username}</h1>
        <h2>Breed: {pet?.Breed.name}</h2>
        <h2>Category: {pet?.Category.name}</h2>
      </main>
    </>
  );
}
